
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASIGNAR BEGIN CONCATENAR CONSTANTE DEF ELSE END ID IF IN PARENT_ABRE PARENT_CIERRA PRINT SIMBOLOProg : BEGIN ListaSent ENDListaSent   : Sent ListaSent \n| SentSent    : Asig \n| Impr \n| FuncAsig : ID ASIGNAR ExprImpr : PRINT IDFunc : DEF ID SIMBOLO ExprtExpr    : ExprtExprt : ID Oper IDOper : CONCATENAROper : IN PARENT_ABRE CONSTANTE PARENT_CIERRAExpr : IF ID IN ID SIMBOLO Exprt ELSE SIMBOLO ExprtExpr : PARENT_ABRE PARENT_CIERRAExpr : ID PARENT_ABRE PARENT_CIERRA'
    
_lr_action_items = {'BEGIN':([0,],[2,]),'$end':([1,11,],[0,-1,]),'ID':([2,4,5,6,7,9,10,13,14,17,18,19,21,23,24,27,29,30,31,33,36,37,40,41,],[8,8,-4,-5,-6,14,15,16,-8,-7,-10,26,28,31,-12,-15,-9,-16,-11,35,-13,28,28,-14,]),'PRINT':([2,4,5,6,7,14,17,18,27,29,30,31,41,],[9,9,-4,-5,-6,-8,-7,-10,-15,-9,-16,-11,-14,]),'DEF':([2,4,5,6,7,14,17,18,27,29,30,31,41,],[10,10,-4,-5,-6,-8,-7,-10,-15,-9,-16,-11,-14,]),'END':([3,4,5,6,7,12,14,17,18,27,29,30,31,41,],[11,-3,-4,-5,-6,-2,-8,-7,-10,-15,-9,-16,-11,-14,]),'ASIGNAR':([8,],[13,]),'IF':([13,],[19,]),'PARENT_ABRE':([13,16,25,],[20,22,32,]),'SIMBOLO':([15,35,39,],[21,37,40,]),'CONCATENAR':([16,28,],[24,24,]),'IN':([16,26,28,],[25,33,25,]),'PARENT_CIERRA':([20,22,34,],[27,30,36,]),'ELSE':([31,38,],[-11,39,]),'CONSTANTE':([32,],[34,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'Prog':([0,],[1,]),'ListaSent':([2,4,],[3,12,]),'Sent':([2,4,],[4,4,]),'Asig':([2,4,],[5,5,]),'Impr':([2,4,],[6,6,]),'Func':([2,4,],[7,7,]),'Expr':([13,],[17,]),'Exprt':([13,21,37,40,],[18,29,38,41,]),'Oper':([16,28,],[23,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> Prog","S'",1,None,None,None),
  ('Prog -> BEGIN ListaSent END','Prog',3,'p_prog','plyparser.py',8),
  ('ListaSent -> Sent ListaSent','ListaSent',2,'p_ListaSent','plyparser.py',13),
  ('ListaSent -> Sent','ListaSent',1,'p_ListaSent','plyparser.py',14),
  ('Sent -> Asig','Sent',1,'p_Sent','plyparser.py',18),
  ('Sent -> Impr','Sent',1,'p_Sent','plyparser.py',19),
  ('Sent -> Func','Sent',1,'p_Sent','plyparser.py',20),
  ('Asig -> ID ASIGNAR Expr','Asig',3,'p_Asig','plyparser.py',24),
  ('Impr -> PRINT ID','Impr',2,'p_Impr','plyparser.py',32),
  ('Func -> DEF ID SIMBOLO Exprt','Func',4,'p_Func','plyparser.py',40),
  ('Expr -> Exprt','Expr',1,'p_Expr','plyparser.py',45),
  ('Exprt -> ID Oper ID','Exprt',3,'p_Exprt','plyparser.py',49),
  ('Oper -> CONCATENAR','Oper',1,'p_Oper_concat','plyparser.py',124),
  ('Oper -> IN PARENT_ABRE CONSTANTE PARENT_CIERRA','Oper',4,'p_Oper_in','plyparser.py',128),
  ('Expr -> IF ID IN ID SIMBOLO Exprt ELSE SIMBOLO Exprt','Expr',9,'p_Condicional','plyparser.py',132),
  ('Expr -> PARENT_ABRE PARENT_CIERRA','Expr',2,'p_Expr_parentesis','plyparser.py',155),
  ('Expr -> ID PARENT_ABRE PARENT_CIERRA','Expr',3,'p_Expr_callfunc','plyparser.py',159),
]
